[package]
name = "cgroup-memory-manager"
version = "0.0.1"
authors = ["Paul Linchpiner <paul@linchpiner.com>"]
edition = "2018"

[dependencies]
byte-unit = "3.1.2"
clap = "3.0.0-beta.1"
env_logger = "0.7.1"
ex = "0.1.3"
failure = "0.1.5"
log = "0.4.0"
walkdir = "2"
